// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: support-ticket.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "supportticket";

export interface ListTicketActivityRequest {
  ticketId: string;
}

export interface ListTicketActivityResponse {
  activities: TicketActivity[];
}

/**
 * oneof meta {
 *     CreatedActivity created = 5;
 *     LockedActivity locked = 6;
 *     AssignedActivity assigned = 7;
 *     StatusChangedActivity status_changed = 8;
 *     PriorityChangedActivity priority_changed = 9;
 *     CommentAddedActivity comment_added = 10;
 *   }
 * }
 */
export interface TicketActivity {
  id: string;
  actor: string;
  type: string;
  timestamp: string;
  meta: Meta | undefined;
}

export interface Meta {
  created?: CreatedActivity | undefined;
  locked?: LockedActivity | undefined;
  assigned?: AssignedActivity | undefined;
  statusChanged?: StatusChangedActivity | undefined;
  priorityChanged?: PriorityChangedActivity | undefined;
  commentAdded?: CommentAddedActivity | undefined;
}

export interface CreatedActivity {
  createdBy: string;
}

export interface LockedActivity {
  locked: boolean;
}

export interface AssignedActivity {
  assignee: string;
}

export interface StatusChangedActivity {
  from: string;
  to: string;
}

export interface PriorityChangedActivity {
  from: string;
  to: string;
}

export interface CommentAddedActivity {
  body: string;
}

export interface Empty {
}

export interface Ticket {
  id: string;
  ticketNo: string;
  orgId: string;
  title: string;
  description: string;
  createdByUserId: string;
  assigneeUserId: string;
  status: string;
  priority: string;
  type: string;
  locked: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Comment {
  id: string;
  ticketId: string;
  orgId: string;
  authorUserId: string;
  body: string;
  createdAt: string;
}

export interface CreateTicketRequest {
  orgId: string;
  orgName: string;
  title: string;
  description: string;
  priority: string;
  type: string;
  createdByUserId: string;
  userEmail: string;
  userName: string;
}

export interface TicketResponse {
  ticket: Ticket | undefined;
}

export interface GetTicketRequest {
  orgId: string;
  ticketId: string;
}

export interface UserContext {
  userId: string;
  role: string;
}

export interface ListTicketsRequest {
  orgId: string;
  status: string[];
  priority: string[];
  assigneeUserId: string;
  /** string createdByUserId = 5; */
  type: string[];
  /** pagination */
  limit: number;
  /** pagination */
  cursor: string;
  /** caller */
  actor: UserContext | undefined;
}

export interface ListTicketsResponse {
  tickets: Ticket[];
  nextCursor: string;
}

export interface AddCommentRequest {
  orgId: string;
  ticketId: string;
  body: string;
  authorUserId: string;
}

export interface CommentResponse {
  comment: Comment | undefined;
}

export interface AssignTicketRequest {
  orgId: string;
  ticketId: string;
  assigneeUserId: string;
  actorUserId: string;
}

export interface TransitionStatusRequest {
  orgId: string;
  ticketId: string;
  newStatus: string;
  actorUserId: string;
}

export interface UpdatePriorityRequest {
  orgId: string;
  ticketId: string;
  newPriority: string;
  actorUserId: string;
}

export interface UpdateTypeRequest {
  orgId: string;
  ticketId: string;
  newType: string;
  actorUserId: string;
}

export interface LockTicketRequest {
  orgId: string;
  ticketId: string;
  /** true = lock, false = unlock */
  lock: boolean;
  actorUserId: string;
}

export const SUPPORTTICKET_PACKAGE_NAME = "supportticket";

export interface SupportTicketClient {
  /** Ticket CRUD */

  createTicket(request: CreateTicketRequest): Observable<TicketResponse>;

  getTicket(request: GetTicketRequest): Observable<TicketResponse>;

  listTickets(request: ListTicketsRequest): Observable<ListTicketsResponse>;

  listTicketActivity(request: ListTicketActivityRequest): Observable<ListTicketActivityResponse>;

  /** Ticket Updates */

  addComment(request: AddCommentRequest): Observable<CommentResponse>;

  assignTicket(request: AssignTicketRequest): Observable<TicketResponse>;

  transitionStatus(request: TransitionStatusRequest): Observable<TicketResponse>;

  updatePriority(request: UpdatePriorityRequest): Observable<TicketResponse>;

  updateType(request: UpdateTypeRequest): Observable<TicketResponse>;

  lockTicket(request: LockTicketRequest): Observable<TicketResponse>;

  /** Internal for gateway health */

  checkHealth(request: Empty): Observable<Empty>;
}

export interface SupportTicketController {
  /** Ticket CRUD */

  createTicket(request: CreateTicketRequest): Promise<TicketResponse> | Observable<TicketResponse> | TicketResponse;

  getTicket(request: GetTicketRequest): Promise<TicketResponse> | Observable<TicketResponse> | TicketResponse;

  listTickets(
    request: ListTicketsRequest,
  ): Promise<ListTicketsResponse> | Observable<ListTicketsResponse> | ListTicketsResponse;

  listTicketActivity(
    request: ListTicketActivityRequest,
  ): Promise<ListTicketActivityResponse> | Observable<ListTicketActivityResponse> | ListTicketActivityResponse;

  /** Ticket Updates */

  addComment(request: AddCommentRequest): Promise<CommentResponse> | Observable<CommentResponse> | CommentResponse;

  assignTicket(request: AssignTicketRequest): Promise<TicketResponse> | Observable<TicketResponse> | TicketResponse;

  transitionStatus(
    request: TransitionStatusRequest,
  ): Promise<TicketResponse> | Observable<TicketResponse> | TicketResponse;

  updatePriority(request: UpdatePriorityRequest): Promise<TicketResponse> | Observable<TicketResponse> | TicketResponse;

  updateType(request: UpdateTypeRequest): Promise<TicketResponse> | Observable<TicketResponse> | TicketResponse;

  lockTicket(request: LockTicketRequest): Promise<TicketResponse> | Observable<TicketResponse> | TicketResponse;

  /** Internal for gateway health */

  checkHealth(request: Empty): Promise<Empty> | Observable<Empty> | Empty;
}

export function SupportTicketControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTicket",
      "getTicket",
      "listTickets",
      "listTicketActivity",
      "addComment",
      "assignTicket",
      "transitionStatus",
      "updatePriority",
      "updateType",
      "lockTicket",
      "checkHealth",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SupportTicket", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SupportTicket", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SUPPORT_TICKET_SERVICE_NAME = "SupportTicket";
